spring.application.name=backend

spring.datasource.url=${jdbc:postgresql://dpg-d8k50i77f7vs7394tm90-a.oregon-postgres.render.com:5432/taskdb_fqiv}
spring.datasource.username=${taskdb}
spring.datasource.password=${TtnQIHjrrfd5OtTasImhPa4zwnad9LwK}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}